langulus_init_git_submodule(Mod-FileSystem)
langulus_init_git_submodule(Mod-Assets-Images)
langulus_init_git_submodule(Mod-Assets-Geometry)
langulus_init_git_submodule(Mod-Assets-Materials)
langulus_init_git_submodule(Mod-FTXUI)
langulus_init_git_submodule(Mod-Physics)
langulus_init_git_submodule(Mod-ASCII)
langulus_init_git_submodule(Mod-InputSDL)
langulus_init_git_submodule(Mod-AI)
langulus_init_git_submodule(Mod-Life)
langulus_init_git_submodule(Mod-Network)
langulus_init_git_submodule(Mod-Storyteller)
langulus_init_git_submodule(Mod-UMS)

if (${LANGULUS_TOASTER_MODE})
	message(STATUS "[LANGULUS] Toaster mode enabled - all graphics modules disabled")
else()
	langulus_init_git_submodule(Mod-GLFW)
	#langulus_init_git_submodule(Mod-ImGui)
	langulus_init_git_submodule(Mod-Vulkan)
endif()


if (EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/Mod-EconomyOfAncientCities")
	add_subdirectory(Mod-EconomyOfAncientCities)
endif()